version: '3.8'

services:
  backend:
    container_name: misyma-backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./apps/backend/data:/app/apps/backend/data
    ports:
      - '5000:5000'

  frontend:
    container_name: misyma-frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - '8080:8080'
