export const BookCategory = {
  literature: 'literatura piękna',
  bellesLettres: 'beletrystyka',
  fantasy: 'fantastyka',
  sciFi: 'fantastyka naukowa',
  poetry: 'poezja',
  kidsLiterature: 'literatura dziecięca',
  youthLiterature: 'literatura młodzieżowa',
  crimeNovel: 'kryminał',
  factLiterature: 'literatura faktu',
  interview: 'reportaż',
  natureLiterature: 'literatura przyrodnicza',
  biography: 'biografia',
  historyNovel: 'powieść historyczna',
  adventure: 'powieść przygodowa',
  popularScience: 'literatura popularnonaukowa',
  scientificLiterature: 'literatura naukowa',
  cookbook: 'książka kucharska',
  album: 'album',
  other: 'inna',
} as const;
