import { Language } from '@common/contracts';

export const languagesArray: { code: Language; name: string }[] = [
  { code: Language['Afar'], name: 'Afar' },
  { code: Language['Abkhazian'], name: 'Abkhazian' },
  { code: Language['Avestan'], name: 'Avestan' },
  { code: Language['Afrikaans'], name: 'Afrikaans' },
  { code: Language['Akan'], name: 'Akan' },
  { code: Language['Amharic'], name: 'Amharic' },
  { code: Language['Aragonese'], name: 'Aragonese' },
  { code: Language['Arabic'], name: 'Arabic' },
  { code: Language['Assamese'], name: 'Assamese' },
  { code: Language['Avaric'], name: 'Avaric' },
  { code: Language['Aymara'], name: 'Aymara' },
  { code: Language['Azerbaijani'], name: 'Azerbaijani' },
  { code: Language['Bashkir'], name: 'Bashkir' },
  { code: Language['Belarusian'], name: 'Belarusian' },
  { code: Language['Bulgarian'], name: 'Bulgarian' },
  { code: Language['Bihari languages'], name: 'Bihari languages' },
  { code: Language['Bislama'], name: 'Bislama' },
  { code: Language['Bambara'], name: 'Bambara' },
  { code: Language['Bengali'], name: 'Bengali' },
  { code: Language['Tibetan'], name: 'Tibetan' },
  { code: Language['Breton'], name: 'Breton' },
  { code: Language['Bosnian'], name: 'Bosnian' },
  { code: Language['Catalan; Valencian'], name: 'Catalan; Valencian' },
  { code: Language['Chechen'], name: 'Chechen' },
  { code: Language['Chamorro'], name: 'Chamorro' },
  { code: Language['Corsican'], name: 'Corsican' },
  { code: Language['Cree'], name: 'Cree' },
  { code: Language['Czech'], name: 'Czech' },
  { code: Language['Chuvash'], name: 'Chuvash' },
  { code: Language['Welsh'], name: 'Welsh' },
  { code: Language['Danish'], name: 'Danish' },
  { code: Language['German'], name: 'German' },
  { code: Language['Dzongkha'], name: 'Dzongkha' },
  { code: Language['Ewe'], name: 'Ewe' },
  { code: Language['Greek'], name: 'Greek' },
  { code: Language['English'], name: 'English' },
  { code: Language['Esperanto'], name: 'Esperanto' },
  { code: Language['Spanish'], name: 'Spanish' },
  { code: Language['Estonian'], name: 'Estonian' },
  { code: Language['Basque'], name: 'Basque' },
  { code: Language['Persian'], name: 'Persian' },
  { code: Language['Fulah'], name: 'Fulah' },
  { code: Language['Finnish'], name: 'Finnish' },
  { code: Language['Fijian'], name: 'Fijian' },
  { code: Language['Faroese'], name: 'Faroese' },
  { code: Language['French'], name: 'French' },
  { code: Language['Western Frisian'], name: 'Western Frisian' },
  { code: Language['Irish'], name: 'Irish' },
  { code: Language['Galician'], name: 'Galician' },
  { code: Language['Guarani'], name: 'Guarani' },
  { code: Language['Gujarati'], name: 'Gujarati' },
  { code: Language['Manx'], name: 'Manx' },
  { code: Language['Hausa'], name: 'Hausa' },
  { code: Language['Hebrew'], name: 'Hebrew' },
  { code: Language['Hindi'], name: 'Hindi' },
  { code: Language['Hiri Motu'], name: 'Hiri Motu' },
  { code: Language['Croatian'], name: 'Croatian' },
  { code: Language['Haitian'], name: 'Haitian' },
  { code: Language['Hungarian'], name: 'Hungarian' },
  { code: Language['Armenian'], name: 'Armenian' },
  { code: Language['Herero'], name: 'Herero' },
  { code: Language['Indonesian'], name: 'Indonesian' },
  { code: Language['Igbo'], name: 'Igbo' },
  { code: Language['Sichuan Yi'], name: 'Sichuan Yi' },
  { code: Language['Inupiaq'], name: 'Inupiaq' },
  { code: Language['Ido'], name: 'Ido' },
  { code: Language['Icelandic'], name: 'Icelandic' },
  { code: Language['Italian'], name: 'Italian' },
  { code: Language['Inuktitut'], name: 'Inuktitut' },
  { code: Language['Japanese'], name: 'Japanese' },
  { code: Language['Javanese'], name: 'Javanese' },
  { code: Language['Georgian'], name: 'Georgian' },
  { code: Language['Kongo'], name: 'Kongo' },
  { code: Language['Kazakh'], name: 'Kazakh' },
  { code: Language['Central Khmer'], name: 'Central Khmer' },
  { code: Language['Kannada'], name: 'Kannada' },
  { code: Language['Korean'], name: 'Korean' },
  { code: Language['Kanuri'], name: 'Kanuri' },
  { code: Language['Kashmiri'], name: 'Kashmiri' },
  { code: Language['Kurdish'], name: 'Kurdish' },
  { code: Language['Komi'], name: 'Komi' },
  { code: Language['Cornish'], name: 'Cornish' },
  { code: Language['Kirghiz; Kyrgyz'], name: 'Kirghiz; Kyrgyz' },
  { code: Language['Latin'], name: 'Latin' },
  { code: Language['Luxembourgish'], name: 'Luxembourgish' },
  { code: Language['Ganda'], name: 'Ganda' },
  { code: Language['Limburgan'], name: 'Limburgan' },
  { code: Language['Lingala'], name: 'Lingala' },
  { code: Language['Lao'], name: 'Lao' },
  { code: Language['Lithuanian'], name: 'Lithuanian' },
  { code: Language['Luba-Katanga'], name: 'Luba-Katanga' },
  { code: Language['Latvian'], name: 'Latvian' },
  { code: Language['Malagasy'], name: 'Malagasy' },
  { code: Language['Marshallese'], name: 'Marshallese' },
  { code: Language['Maori'], name: 'Maori' },
  { code: Language['Macedonian'], name: 'Macedonian' },
  { code: Language['Malayalam'], name: 'Malayalam' },
  { code: Language['Mongolian'], name: 'Mongolian' },
  { code: Language['Marathi'], name: 'Marathi' },
  { code: Language['Malay'], name: 'Malay' },
  { code: Language['Maltese'], name: 'Maltese' },
  { code: Language['Burmese'], name: 'Burmese' },
  { code: Language['Nauru'], name: 'Nauru' },
  { code: Language['Nepali'], name: 'Nepali' },
  { code: Language['Ndonga'], name: 'Ndonga' },
  { code: Language['Dutch'], name: 'Dutch' },
  { code: Language['Norwegian'], name: 'Norwegian' },
  { code: Language['Ojibwa'], name: 'Ojibwa' },
  { code: Language['Oromo'], name: 'Oromo' },
  { code: Language['Oriya'], name: 'Oriya' },
  { code: Language['Punjabi'], name: 'Punjabi' },
  { code: Language['Pali'], name: 'Pali' },
  { code: Language['Polish'], name: 'Polish' },
  { code: Language['Portuguese'], name: 'Portuguese' },
  { code: Language['Quechua'], name: 'Quechua' },
  { code: Language['Romansh'], name: 'Romansh' },
  { code: Language['Rundi'], name: 'Rundi' },
  { code: Language['Romanian'], name: 'Romanian' },
  { code: Language['Russian'], name: 'Russian' },
  { code: Language['Kinyarwanda'], name: 'Kinyarwanda' },
  { code: Language['Sanskrit'], name: 'Sanskrit' },
  { code: Language['Sardinian'], name: 'Sardinian' },
  { code: Language['Sindhi'], name: 'Sindhi' },
  { code: Language['Northern Sami'], name: 'Northern Sami' },
  { code: Language['Sango'], name: 'Sango' },
  { code: Language['Sinhala'], name: 'Sinhala' },
  { code: Language['Slovak'], name: 'Slovak' },
  { code: Language['Slovenian'], name: 'Slovenian' },
  { code: Language['Samoan'], name: 'Samoan' },
  { code: Language['Shona'], name: 'Shona' },
  { code: Language['Somali'], name: 'Somali' },
  { code: Language['Albanian'], name: 'Albanian' },
  { code: Language['Serbian'], name: 'Serbian' },
  { code: Language['Swati'], name: 'Swati' },
  { code: Language['Sotho, Southern'], name: 'Sotho, Southern' },
  { code: Language['Sundanese'], name: 'Sundanese' },
  { code: Language['Swedish'], name: 'Swedish' },
  { code: Language['Swahili'], name: 'Swahili' },
  { code: Language['Tamil'], name: 'Tamil' },
  { code: Language['Telugu'], name: 'Telugu' },
  { code: Language['Tajik'], name: 'Tajik' },
  { code: Language['Thai'], name: 'Thai' },
  { code: Language['Tigrinya'], name: 'Tigrinya' },
  { code: Language['Turkmen'], name: 'Turkmen' },
  { code: Language['Tagalog'], name: 'Tagalog' },
  { code: Language['Tswana'], name: 'Tswana' },
  { code: Language['Turkish'], name: 'Turkish' },
  { code: Language['Tsonga'], name: 'Tsonga' },
  { code: Language['Tatar'], name: 'Tatar' },
  { code: Language['Twi'], name: 'Twi' },
  { code: Language['Tahitian'], name: 'Tahitian' },
  { code: Language['Uyghur'], name: 'Uyghur' },
  { code: Language['Ukrainian'], name: 'Ukrainian' },
  { code: Language['Urdu'], name: 'Urdu' },
  { code: Language['Uzbek'], name: 'Uzbek' },
  { code: Language['Venda'], name: 'Venda' },
  { code: Language['Vietnamese'], name: 'Vietnamese' },
  { code: Language['Volapük'], name: 'Volapük' },
  { code: Language['Walloon'], name: 'Walloon' },
  { code: Language['Wolof'], name: 'Wolof' },
  { code: Language['Xhosa'], name: 'Xhosa' },
  { code: Language['Yiddish'], name: 'Yiddish' },
  { code: Language['Yoruba'], name: 'Yoruba' },
  { code: Language['Zhuang'], name: 'Zhuang' },
  { code: Language['Chinese'], name: 'Chinese' },
  { code: Language['Zulu'], name: 'Zulu' },
];

export enum Languages {
  Afar = 'Afar',
  Abkhazian = 'Abchaski',
  Avestan = 'Awecki',
  Afrikaans = 'Afrikaans',
  Akan = 'Akan',
  Amharic = 'Amharski',
  Aragonese = 'Aragoński',
  Arabic = 'Arabski',
  Assamese = 'Asamski',
  Avaric = 'Awaricki',
  Aymara = 'Ajmarski',
  Azerbaijani = 'Azerbejdżański',
  Bashkir = 'Baszkirski',
  Belarusian = 'Białoruski',
  Bulgarian = 'Bułgarski',
  'Bihari languages' = 'Języki biharijskie',
  Bislama = 'Bislama',
  Bambara = 'Bambarski',
  Bengali = 'Bengalski',
  Tibetan = 'Tybetański',
  Breton = 'Bretoński',
  Bosnian = 'Bośniacki',
  'Catalan; Valencian' = 'Kataloński; Walencki',
  Chechen = 'Czeczeński',
  Chamorro = 'Chamorro',
  Corsican = 'Korsykański',
  Cree = 'Cree',
  Czech = 'Czeski',
  Chuvash = 'Czuwaszski',
  Welsh = 'Walon',
  Danish = 'Duński',
  German = 'Niemiecki',
  Dzongkha = 'Dzongkha',
  Ewe = 'Ewe',
  Greek = 'Grecki',
  English = 'Angielski',
  Esperanto = 'Esperanto',
  Spanish = 'Hiszpański',
  Estonian = 'Estoński',
  Basque = 'Baskijski',
  Persian = 'Perski',
  Fulah = 'Fulah',
  Finnish = 'Fiński',
  Fijian = 'Fidżijski',
  Faroese = 'Wysp Owczych',
  French = 'Francuski',
  'Western Frisian' = 'Fryzyjski zachodni',
  Irish = 'Irlandzki',
  Galician = 'Galicyjski',
  Guarani = 'Guarani',
  Gujarati = 'Gujarati',
  Manx = 'Manx',
  Hausa = 'Hausa',
  Hebrew = 'Hebrajski',
  Hindi = 'Hindi',
  'Hiri Motu' = 'Hiri Motu',
  Croatian = 'Chorwacki',
  Haitian = 'Haiti Creole',
  Hungarian = 'Węgierski',
  Armenian = 'Ormiański',
  Herero = 'Herero',
  Indonesian = 'Indonezyjski',
  Igbo = 'Igbo',
  'Sichuan Yi' = 'Syczuanski Yi',
  Inupiaq = 'Inupiak',
  Ido = 'Ido',
  Icelandic = 'Islandzki',
  Italian = 'Włoski',
  Inuktitut = 'Inuktitut',
  Japanese = 'Japoński',
  Javanese = 'Jawajski',
  Georgian = 'Gruziński',
  Kongo = 'Kongijski',
  Kazakh = 'Kazachski',
  'Central Khmer' = 'Język khmerski centralny',
  Kannada = 'Kannada',
  Korean = 'Koreański',
  Kanuri = 'Kanuri',
  Kashmiri = 'Kaszmirski',
  Kurdish = 'Kurdski',
  Komi = 'Komii',
  Cornish = 'Kornijski',
  'Kirghiz; Kyrgyz' = 'Kirgiski; Kyrgyz',
  Latin = 'Łaciński',
  Luxembourgish = 'Luksemburski',
  Ganda = 'Gandijski',
  Limburgan = 'Limburski',
  Lingala = 'Lingala',
  Lao = 'Laotański',
  Lithuanian = 'Litewski',
  'Luba-Katanga' = 'Luba-Katanga',
  Latvian = 'Łotewski',
  Malagasy = 'Malgaski',
  Marshallese = 'Marszalski',
  Maori = 'Maoryski',
  Macedonian = 'Macedoński',
  Malayalam = 'Malayalam',
  Mongolian = 'Mongolski',
  Marathi = 'Marathi',
  Malay = 'Malajski',
  Maltese = 'Maltański',
  Burmese = 'Birmański',
  Nauru = 'Nauruański',
  Nepali = 'Nepalski',
  Ndonga = 'Ndonga',
  Dutch = 'Holenderski',
  Norwegian = 'Norweski',
  Ojibwa = 'Ojibwa',
  Oriya = 'Orija',
  Punjabi = 'Pendżabski',
  Pali = 'Pali',
  Polish = 'Polski',
  Portuguese = 'Portugalski',
  Quechua = 'Keczua',
  Romansh = 'Reto-Roman',
  Rundi = 'Rundi',
  Romanian = 'Rumuński',
  Russian = 'Rosyjski',
  Kinyarwanda = 'Kinyarwanda',
  Sanskrit = 'Sanskryt',
  Sardinian = 'Sardyński',
  Sindhi = 'Sindhi',
  'Northern Sami' = 'Północny sami',
  Sango = 'Sango',
  Sinhala = 'Syngaleski',
  Slovak = 'Słowacki',
  Slovenian = 'Słoweński',
  Samoan = 'Samoński',
  Shona = 'Shona',
  Somali = 'Somalijski',
  Albanian = 'Albański',
  Serbian = 'Serbski',
  Swati = 'Swati',
  'Sotho, Southern' = 'Sotho, Południowy',
  Sundanese = 'Sundajski',
  Swedish = 'Szwedzki',
  Swahili = 'Suahili',
  Tamil = 'Tamilski',
  Telugu = 'Telugu',
  Tajik = 'Tadżycki',
  Thai = 'Tajski',
  Tigrinya = 'Tigrinia',
  Turkmen = 'Turkmeński',
  Tagalog = 'Tagalski',
  Tswana = 'Tswana',
  Turkish = 'Turecki',
  Tsonga = 'Tsonga',
  Tatar = 'Tatarski',
  Twi = 'Twi',
  Tahitian = 'Tahitański',
  Uyghur = 'Ujgurski',
  Ukrainian = 'Ukraiński',
  Urdu = 'Urdu',
  Uzbek = 'Uzbecki',
  Venda = 'Venda',
  Vietnamese = 'Wietnamski',
  Volapük = 'Volapük',
  Walloon = 'Waloński',
  Wolof = 'Wolof',
  Xhosa = 'Xhosa',
  Yiddish = 'Jidysz',
  Yoruba = 'Joruba',
  Zhuang = 'Zhuang',
  Chinese = 'Chiński',
  Zulu = 'Zuluski',
}

export const ReversedLanguages = {
  aa: 'Afar',
  ab: 'Abchaski',
  ae: 'Awecki',
  af: 'Afrikaans',
  ak: 'Akan',
  am: 'Amharski',
  an: 'Aragoński',
  ar: 'Arabski',
  as: 'Asamski',
  av: 'Awaricki',
  ay: 'Ajmarski',
  az: 'Azerbejdżański',
  ba: 'Baszkirski',
  be: 'Białoruski',
  bg: 'Bułgarski',
  bh: 'Języki biharijskie',
  bi: 'Bislama',
  bm: 'Bambarski',
  bn: 'Bengalski',
  bo: 'Tybetański',
  br: 'Bretoński',
  bs: 'Bośniacki',
  ca: 'Kataloński; Walencki',
  ce: 'Czeczeński',
  ch: 'Chamorro',
  co: 'Korsykański',
  cr: 'Cree',
  cs: 'Czeski',
  cv: 'Czuwaszski',
  cy: 'Walon',
  da: 'Duński',
  de: 'Niemiecki',
  dz: 'Dzongkha',
  ee: 'Ewe',
  el: 'Grecki',
  en: 'Angielski',
  eo: 'Esperanto',
  es: 'Hiszpański',
  et: 'Estoński',
  eu: 'Baskijski',
  fa: 'Perski',
  ff: 'Fulah',
  fi: 'Fiński',
  fj: 'Fidżijski',
  fo: 'Wysp Owczych',
  fr: 'Francuski',
  fy: 'Fryzyjski zachodni',
  ga: 'Irlandzki',
  gl: 'Galicyjski',
  gn: 'Guarani',
  gu: 'Gujarati',
  gv: 'Manx',
  ha: 'Hausa',
  he: 'Hebrajski',
  hi: 'Hindi',
  ho: 'Hiri Motu',
  hr: 'Chorwacki',
  ht: 'Haiti Creole',
  hu: 'Węgierski',
  hy: 'Ormiański',
  hz: 'Herero',
  id: 'Indonezyjski',
  ig: 'Igbo',
  ii: 'Syczuanski Yi',
  ik: 'Inupiaq',
  io: 'Ido',
  is: 'Islandzki',
  it: 'Włoski',
  iu: 'Inuktitut',
  ja: 'Japoński',
  jv: 'Jawajski',
  ka: 'Gruziński',
  kg: 'Kongijski',
  kk: 'Kazachski',
  km: 'Język khmerski centralny',
  kn: 'Kannada',
  ko: 'Koreański',
  kr: 'Kanuri',
  ks: 'Kaszmirski',
  ku: 'Kurdski',
  kv: 'Komii',
  kw: 'Kornijski',
  ky: 'Kirgiski; Kyrgyz',
  la: 'Łaciński',
  lb: 'Luksemburski',
  lg: 'Gandijski',
  li: 'Limburski',
  ln: 'Lingala',
  lo: 'Laotański',
  lt: 'Litewski',
  lu: 'Luba-Katanga',
  lv: 'Łotewski',
  mg: 'Malgaski',
  mh: 'Marszalski',
  mi: 'Maoryski',
  mk: 'Macedoński',
  ml: 'Malayalam',
  mn: 'Mongolski',
  mr: 'Marathi',
  ms: 'Malajski',
  mt: 'Maltański',
  my: 'Birmański',
  na: 'Nauruański',
  ne: 'Nepalski',
  ng: 'Ndonga',
  nl: 'Holenderski',
  no: 'Norweski',
  oj: 'Ojibwa',
  om: 'Oromo',
  or: 'Orija',
  pa: 'Pendżabski',
  pi: 'Pali',
  pl: 'Polski',
  pt: 'Portugalski',
  qu: 'Keczua',
  rm: 'Reto-Roman',
  rn: 'Rundi',
  ro: 'Rumuński',
  ru: 'Rosyjski',
  rw: 'Kinyarwanda',
  sa: 'Sanskryt',
  sc: 'Sardyński',
  sd: 'Sindhi',
  se: 'Północny sami',
  sg: 'Sango',
  si: 'Syngaleski',
  sk: 'Słowacki',
  sl: 'Słoweński',
  sm: 'Samoński',
  sn: 'Shona',
  so: 'Somalijski',
  sq: 'Albański',
  sr: 'Serbski',
  ss: 'Swati',
  st: 'Sotho, Południowy',
  su: 'Sundajski',
  sv: 'Szwedzki',
  sw: 'Suahili',
  ta: 'Tamilski',
  te: 'Telugu',
  tg: 'Tadżycki',
  th: 'Tajski',
  ti: 'Tigrinia',
  tk: 'Turkmeński',
  tl: 'Tagalski',
  tn: 'Tswana',
  tr: 'Turecki',
  ts: 'Tsonga',
  tt: 'Tatarski',
  tw: 'Twi',
  ty: 'Tahitański',
  ug: 'Ujgurski',
  uk: 'Ukraiński',
  ur: 'Urdu',
  uz: 'Uzbecki',
  ve: 'Venda',
  vi: 'Wietnamski',
  vo: 'Volapük',
  wa: 'Waloński',
  wo: 'Wolof',
  xh: 'Xhosa',
  yi: 'Jidysz',
  yo: 'Joruba',
  za: 'Zhuang',
  zh: 'Chiński',
  zu: 'Zuluski',
} as const;
