import { Language, languages } from '@common/contracts';

export const languagesArray: { code: Language; name: string }[] = [
  { code: languages['Afar'], name: 'Afar' },
  { code: languages['Abkhazian'], name: 'Abkhazian' },
  { code: languages['Avestan'], name: 'Avestan' },
  { code: languages['Afrikaans'], name: 'Afrikaans' },
  { code: languages['Akan'], name: 'Akan' },
  { code: languages['Amharic'], name: 'Amharic' },
  { code: languages['Aragonese'], name: 'Aragonese' },
  { code: languages['Arabic'], name: 'Arabic' },
  { code: languages['Assamese'], name: 'Assamese' },
  { code: languages['Avaric'], name: 'Avaric' },
  { code: languages['Aymara'], name: 'Aymara' },
  { code: languages['Azerbaijani'], name: 'Azerbaijani' },
  { code: languages['Bashkir'], name: 'Bashkir' },
  { code: languages['Belarusian'], name: 'Belarusian' },
  { code: languages['Bulgarian'], name: 'Bulgarian' },
  { code: languages['Bihari languages'], name: 'Bihari languages' },
  { code: languages['Bislama'], name: 'Bislama' },
  { code: languages['Bambara'], name: 'Bambara' },
  { code: languages['Bengali'], name: 'Bengali' },
  { code: languages['Tibetan'], name: 'Tibetan' },
  { code: languages['Breton'], name: 'Breton' },
  { code: languages['Bosnian'], name: 'Bosnian' },
  { code: languages['Catalan; Valencian'], name: 'Catalan; Valencian' },
  { code: languages['Chechen'], name: 'Chechen' },
  { code: languages['Chamorro'], name: 'Chamorro' },
  { code: languages['Corsican'], name: 'Corsican' },
  { code: languages['Cree'], name: 'Cree' },
  { code: languages['Czech'], name: 'Czech' },
  { code: languages['Chuvash'], name: 'Chuvash' },
  { code: languages['Welsh'], name: 'Welsh' },
  { code: languages['Danish'], name: 'Danish' },
  { code: languages['German'], name: 'German' },
  { code: languages['Dzongkha'], name: 'Dzongkha' },
  { code: languages['Ewe'], name: 'Ewe' },
  { code: languages['Greek'], name: 'Greek' },
  { code: languages['English'], name: 'English' },
  { code: languages['Esperanto'], name: 'Esperanto' },
  { code: languages['Spanish'], name: 'Spanish' },
  { code: languages['Estonian'], name: 'Estonian' },
  { code: languages['Basque'], name: 'Basque' },
  { code: languages['Persian'], name: 'Persian' },
  { code: languages['Fulah'], name: 'Fulah' },
  { code: languages['Finnish'], name: 'Finnish' },
  { code: languages['Fijian'], name: 'Fijian' },
  { code: languages['Faroese'], name: 'Faroese' },
  { code: languages['French'], name: 'French' },
  { code: languages['Western Frisian'], name: 'Western Frisian' },
  { code: languages['Irish'], name: 'Irish' },
  { code: languages['Galician'], name: 'Galician' },
  { code: languages['Guarani'], name: 'Guarani' },
  { code: languages['Gujarati'], name: 'Gujarati' },
  { code: languages['Manx'], name: 'Manx' },
  { code: languages['Hausa'], name: 'Hausa' },
  { code: languages['Hebrew'], name: 'Hebrew' },
  { code: languages['Hindi'], name: 'Hindi' },
  { code: languages['Hiri Motu'], name: 'Hiri Motu' },
  { code: languages['Croatian'], name: 'Croatian' },
  { code: languages['Haitian'], name: 'Haitian' },
  { code: languages['Hungarian'], name: 'Hungarian' },
  { code: languages['Armenian'], name: 'Armenian' },
  { code: languages['Herero'], name: 'Herero' },
  { code: languages['Indonesian'], name: 'Indonesian' },
  { code: languages['Igbo'], name: 'Igbo' },
  { code: languages['Sichuan Yi'], name: 'Sichuan Yi' },
  { code: languages['Inupiaq'], name: 'Inupiaq' },
  { code: languages['Ido'], name: 'Ido' },
  { code: languages['Icelandic'], name: 'Icelandic' },
  { code: languages['Italian'], name: 'Italian' },
  { code: languages['Inuktitut'], name: 'Inuktitut' },
  { code: languages['Japanese'], name: 'Japanese' },
  { code: languages['Javanese'], name: 'Javanese' },
  { code: languages['Georgian'], name: 'Georgian' },
  { code: languages['Kongo'], name: 'Kongo' },
  { code: languages['Kazakh'], name: 'Kazakh' },
  { code: languages['Central Khmer'], name: 'Central Khmer' },
  { code: languages['Kannada'], name: 'Kannada' },
  { code: languages['Korean'], name: 'Korean' },
  { code: languages['Kanuri'], name: 'Kanuri' },
  { code: languages['Kashmiri'], name: 'Kashmiri' },
  { code: languages['Kurdish'], name: 'Kurdish' },
  { code: languages['Komi'], name: 'Komi' },
  { code: languages['Cornish'], name: 'Cornish' },
  { code: languages['Kirghiz; Kyrgyz'], name: 'Kirghiz; Kyrgyz' },
  { code: languages['Latin'], name: 'Latin' },
  { code: languages['Luxembourgish'], name: 'Luxembourgish' },
  { code: languages['Ganda'], name: 'Ganda' },
  { code: languages['Limburgan'], name: 'Limburgan' },
  { code: languages['Lingala'], name: 'Lingala' },
  { code: languages['Lao'], name: 'Lao' },
  { code: languages['Lithuanian'], name: 'Lithuanian' },
  { code: languages['Luba-Katanga'], name: 'Luba-Katanga' },
  { code: languages['Latvian'], name: 'Latvian' },
  { code: languages['Malagasy'], name: 'Malagasy' },
  { code: languages['Marshallese'], name: 'Marshallese' },
  { code: languages['Maori'], name: 'Maori' },
  { code: languages['Macedonian'], name: 'Macedonian' },
  { code: languages['Malayalam'], name: 'Malayalam' },
  { code: languages['Mongolian'], name: 'Mongolian' },
  { code: languages['Marathi'], name: 'Marathi' },
  { code: languages['Malay'], name: 'Malay' },
  { code: languages['Maltese'], name: 'Maltese' },
  { code: languages['Burmese'], name: 'Burmese' },
  { code: languages['Nauru'], name: 'Nauru' },
  { code: languages['Nepali'], name: 'Nepali' },
  { code: languages['Ndonga'], name: 'Ndonga' },
  { code: languages['Dutch'], name: 'Dutch' },
  { code: languages['Norwegian'], name: 'Norwegian' },
  { code: languages['Ojibwa'], name: 'Ojibwa' },
  { code: languages['Oromo'], name: 'Oromo' },
  { code: languages['Oriya'], name: 'Oriya' },
  { code: languages['Punjabi'], name: 'Punjabi' },
  { code: languages['Pali'], name: 'Pali' },
  { code: languages['Polish'], name: 'Polish' },
  { code: languages['Portuguese'], name: 'Portuguese' },
  { code: languages['Quechua'], name: 'Quechua' },
  { code: languages['Romansh'], name: 'Romansh' },
  { code: languages['Rundi'], name: 'Rundi' },
  { code: languages['Romanian'], name: 'Romanian' },
  { code: languages['Russian'], name: 'Russian' },
  { code: languages['Kinyarwanda'], name: 'Kinyarwanda' },
  { code: languages['Sanskrit'], name: 'Sanskrit' },
  { code: languages['Sardinian'], name: 'Sardinian' },
  { code: languages['Sindhi'], name: 'Sindhi' },
  { code: languages['Northern Sami'], name: 'Northern Sami' },
  { code: languages['Sango'], name: 'Sango' },
  { code: languages['Sinhala'], name: 'Sinhala' },
  { code: languages['Slovak'], name: 'Slovak' },
  { code: languages['Slovenian'], name: 'Slovenian' },
  { code: languages['Samoan'], name: 'Samoan' },
  { code: languages['Shona'], name: 'Shona' },
  { code: languages['Somali'], name: 'Somali' },
  { code: languages['Albanian'], name: 'Albanian' },
  { code: languages['Serbian'], name: 'Serbian' },
  { code: languages['Swati'], name: 'Swati' },
  { code: languages['Sotho, Southern'], name: 'Sotho, Southern' },
  { code: languages['Sundanese'], name: 'Sundanese' },
  { code: languages['Swedish'], name: 'Swedish' },
  { code: languages['Swahili'], name: 'Swahili' },
  { code: languages['Tamil'], name: 'Tamil' },
  { code: languages['Telugu'], name: 'Telugu' },
  { code: languages['Tajik'], name: 'Tajik' },
  { code: languages['Thai'], name: 'Thai' },
  { code: languages['Tigrinya'], name: 'Tigrinya' },
  { code: languages['Turkmen'], name: 'Turkmen' },
  { code: languages['Tagalog'], name: 'Tagalog' },
  { code: languages['Tswana'], name: 'Tswana' },
  { code: languages['Turkish'], name: 'Turkish' },
  { code: languages['Tsonga'], name: 'Tsonga' },
  { code: languages['Tatar'], name: 'Tatar' },
  { code: languages['Twi'], name: 'Twi' },
  { code: languages['Tahitian'], name: 'Tahitian' },
  { code: languages['Uyghur'], name: 'Uyghur' },
  { code: languages['Ukrainian'], name: 'Ukrainian' },
  { code: languages['Urdu'], name: 'Urdu' },
  { code: languages['Uzbek'], name: 'Uzbek' },
  { code: languages['Venda'], name: 'Venda' },
  { code: languages['Vietnamese'], name: 'Vietnamese' },
  { code: languages['Volapük'], name: 'Volapük' },
  { code: languages['Walloon'], name: 'Walloon' },
  { code: languages['Wolof'], name: 'Wolof' },
  { code: languages['Xhosa'], name: 'Xhosa' },
  { code: languages['Yiddish'], name: 'Yiddish' },
  { code: languages['Yoruba'], name: 'Yoruba' },
  { code: languages['Zhuang'], name: 'Zhuang' },
  { code: languages['Chinese'], name: 'Chinese' },
  { code: languages['Zulu'], name: 'Zulu' },
];

export enum Languages {
  Afar = 'Afar',
  Abkhazian = 'Abchaski',
  Avestan = 'Awecki',
  Afrikaans = 'Afrikaans',
  Akan = 'Akan',
  Amharic = 'Amharski',
  Aragonese = 'Aragoński',
  Arabic = 'Arabski',
  Assamese = 'Asamski',
  Avaric = 'Awaricki',
  Aymara = 'Ajmarski',
  Azerbaijani = 'Azerbejdżański',
  Bashkir = 'Baszkirski',
  Belarusian = 'Białoruski',
  Bulgarian = 'Bułgarski',
  'Bihari languages' = 'Języki biharijskie',
  Bislama = 'Bislama',
  Bambara = 'Bambarski',
  Bengali = 'Bengalski',
  Tibetan = 'Tybetański',
  Breton = 'Bretoński',
  Bosnian = 'Bośniacki',
  'Catalan; Valencian' = 'Kataloński; Walencki',
  Chechen = 'Czeczeński',
  Chamorro = 'Chamorro',
  Corsican = 'Korsykański',
  Cree = 'Cree',
  Czech = 'Czeski',
  Chuvash = 'Czuwaszski',
  Welsh = 'Walon',
  Danish = 'Duński',
  German = 'Niemiecki',
  Dzongkha = 'Dzongkha',
  Ewe = 'Ewe',
  Greek = 'Grecki',
  English = 'Angielski',
  Esperanto = 'Esperanto',
  Spanish = 'Hiszpański',
  Estonian = 'Estoński',
  Basque = 'Baskijski',
  Persian = 'Perski',
  Fulah = 'Fulah',
  Finnish = 'Fiński',
  Fijian = 'Fidżijski',
  Faroese = 'Wysp Owczych',
  French = 'Francuski',
  'Western Frisian' = 'Fryzyjski zachodni',
  Irish = 'Irlandzki',
  Galician = 'Galicyjski',
  Guarani = 'Guarani',
  Gujarati = 'Gujarati',
  Manx = 'Manx',
  Hausa = 'Hausa',
  Hebrew = 'Hebrajski',
  Hindi = 'Hindi',
  'Hiri Motu' = 'Hiri Motu',
  Croatian = 'Chorwacki',
  Haitian = 'Haiti Creole',
  Hungarian = 'Węgierski',
  Armenian = 'Ormiański',
  Herero = 'Herero',
  Indonesian = 'Indonezyjski',
  Igbo = 'Igbo',
  'Sichuan Yi' = 'Syczuanski Yi',
  Inupiaq = 'Inupiak',
  Ido = 'Ido',
  Icelandic = 'Islandzki',
  Italian = 'Włoski',
  Inuktitut = 'Inuktitut',
  Japanese = 'Japoński',
  Javanese = 'Jawajski',
  Georgian = 'Gruziński',
  Kongo = 'Kongijski',
  Kazakh = 'Kazachski',
  'Central Khmer' = 'Język khmerski centralny',
  Kannada = 'Kannada',
  Korean = 'Koreański',
  Kanuri = 'Kanuri',
  Kashmiri = 'Kaszmirski',
  Kurdish = 'Kurdski',
  Komi = 'Komii',
  Cornish = 'Kornijski',
  'Kirghiz; Kyrgyz' = 'Kirgiski; Kyrgyz',
  Latin = 'Łaciński',
  Luxembourgish = 'Luksemburski',
  Ganda = 'Gandijski',
  Limburgan = 'Limburski',
  Lingala = 'Lingala',
  Lao = 'Laotański',
  Lithuanian = 'Litewski',
  'Luba-Katanga' = 'Luba-Katanga',
  Latvian = 'Łotewski',
  Malagasy = 'Malgaski',
  Marshallese = 'Marszalski',
  Maori = 'Maoryski',
  Macedonian = 'Macedoński',
  Malayalam = 'Malayalam',
  Mongolian = 'Mongolski',
  Marathi = 'Marathi',
  Malay = 'Malajski',
  Maltese = 'Maltański',
  Burmese = 'Birmański',
  Nauru = 'Nauruański',
  Nepali = 'Nepalski',
  Ndonga = 'Ndonga',
  Dutch = 'Holenderski',
  Norwegian = 'Norweski',
  Ojibwa = 'Ojibwa',
  Oriya = 'Orija',
  Punjabi = 'Pendżabski',
  Pali = 'Pali',
  Polish = 'Polski',
  Portuguese = 'Portugalski',
  Quechua = 'Keczua',
  Romansh = 'Reto-Roman',
  Rundi = 'Rundi',
  Romanian = 'Rumuński',
  Russian = 'Rosyjski',
  Kinyarwanda = 'Kinyarwanda',
  Sanskrit = 'Sanskryt',
  Sardinian = 'Sardyński',
  Sindhi = 'Sindhi',
  'Northern Sami' = 'Północny sami',
  Sango = 'Sango',
  Sinhala = 'Syngaleski',
  Slovak = 'Słowacki',
  Slovenian = 'Słoweński',
  Samoan = 'Samoński',
  Shona = 'Shona',
  Somali = 'Somalijski',
  Albanian = 'Albański',
  Serbian = 'Serbski',
  Swati = 'Swati',
  'Sotho, Southern' = 'Sotho, Południowy',
  Sundanese = 'Sundajski',
  Swedish = 'Szwedzki',
  Swahili = 'Suahili',
  Tamil = 'Tamilski',
  Telugu = 'Telugu',
  Tajik = 'Tadżycki',
  Thai = 'Tajski',
  Tigrinya = 'Tigrinia',
  Turkmen = 'Turkmeński',
  Tagalog = 'Tagalski',
  Tswana = 'Tswana',
  Turkish = 'Turecki',
  Tsonga = 'Tsonga',
  Tatar = 'Tatarski',
  Twi = 'Twi',
  Tahitian = 'Tahitański',
  Uyghur = 'Ujgurski',
  Ukrainian = 'Ukraiński',
  Urdu = 'Urdu',
  Uzbek = 'Uzbecki',
  Venda = 'Venda',
  Vietnamese = 'Wietnamski',
  Volapük = 'Volapük',
  Walloon = 'Waloński',
  Wolof = 'Wolof',
  Xhosa = 'Xhosa',
  Yiddish = 'Jidysz',
  Yoruba = 'Joruba',
  Zhuang = 'Zhuang',
  Chinese = 'Chiński',
  Zulu = 'Zuluski',
}

export enum LanguagesValues {
  Afar = 'Afar',
  Abchaski = 'Abkhazian',
  Awecki = 'Avestan',
  Afrikaans = 'Afrikaans',
  Akan = 'Akan',
  Amharski = 'Amharic',
  Aragoński = 'Aragonese',
  Arabski = 'Arabic',
  Asamski = 'Assamese',
  Awaricki = 'Avaric',
  Ajmarski = 'Aymara',
  Azerbejdżański = 'Azerbaijani',
  Baszkirski = 'Bashkir',
  Białoruski = 'Belarusian',
  Bułgarski = 'Bulgarian',
  'Języki biharijskie' = 'Bihari languages',
  Bislama = 'Bislama',
  Bambarski = 'Bambara',
  Bengalski = 'Bengali',
  Tybetański = 'Tibetan',
  Bretoński = 'Breton',
  Bośniacki = 'Bosnian',
  'Kataloński; Walencki' = 'Catalan; Valencian',
  Czeczeński = 'Chechen',
  Chamorro = 'Chamorro',
  Korsykański = 'Corsican',
  Cree = 'Cree',
  Czeski = 'Czech',
  Czuwaszski = 'Chuvash',
  Walon = 'Welsh',
  Duński = 'Danish',
  Niemiecki = 'German',
  Dzongkha = 'Dzongkha',
  Ewe = 'Ewe',
  Grecki = 'Greek',
  Angielski = 'English',
  Esperanto = 'Esperanto',
  Hiszpański = 'Spanish',
  Estoński = 'Estonian',
  Baskijski = 'Basque',
  Perski = 'Persian',
  Fulah = 'Fulah',
  Fiński = 'Finnish',
  Fidżijski = 'Fijian',
  'Wysp Owczych' = 'Faroese',
  Francuski = 'French',
  'Fryzyjski zachodni' = 'Western Frisian',
  Irlandzki = 'Irish',
  Galicyjski = 'Galician',
  Guarani = 'Guarani',
  Gujarati = 'Gujarati',
  Manx = 'Manx',
  Hausa = 'Hausa',
  Hebrajski = 'Hebrew',
  Hindi = 'Hindi',
  'Hiri Motu' = 'Hiri Motu',
  Chorwacki = 'Croatian',
  'Haiti Creole' = 'Haitian',
  Węgierski = 'Hungarian',
  Ormiański = 'Armenian',
  Herero = 'Herero',
  Indonezyjski = 'Indonesian',
  Igbo = 'Igbo',
  'Syczuanski Yi' = 'Sichuan Yi',
  Inupiak = 'Inupiaq',
  Ido = 'Ido',
  Islandzki = 'Icelandic',
  Włoski = 'Italian',
  Inuktitut = 'Inuktitut',
  Japoński = 'Japanese',
  Jawajski = 'Javanese',
  Gruziński = 'Georgian',
  Kongijski = 'Kongo',
  Kazachski = 'Kazakh',
  'Język khmerski centralny' = 'Central Khmer',
  Kannada = 'Kannada',
  Koreański = 'Korean',
  Kanuri = 'Kanuri',
  Kaszmirski = 'Kashmiri',
  Kurdski = 'Kurdish',
  Komii = 'Komi',
  Kornijski = 'Cornish',
  'Kirgiski; Kyrgyz' = 'Kirghiz; Kyrgyz',
  Łaciński = 'Latin',
  Luksemburski = 'Luxembourgish',
  Gandijski = 'Ganda',
  Limburski = 'Limburgan',
  Lingala = 'Lingala',
  Laotański = 'Lao',
  Litewski = 'Lithuanian',
  'Luba-Katanga' = 'Luba-Katanga',
  Łotewski = 'Latvian',
  Malgaski = 'Malagasy',
  Marszalski = 'Marshallese',
  Maoryski = 'Maori',
  Macedoński = 'Macedonian',
  Malayalam = 'Malayalam',
  Mongolski = 'Mongolian',
  Marathi = 'Marathi',
  Malajski = 'Malay',
  Maltański = 'Maltese',
  Birmański = 'Burmese',
  Nauruański = 'Nauru',
  Nepalski = 'Nepali',
  Ndonga = 'Ndonga',
  Holenderski = 'Dutch',
  Norweski = 'Norwegian',
  Ojibwa = 'Ojibwa',
  Orija = 'Oriya',
  Pendżabski = 'Punjabi',
  Pali = 'Pali',
  Polski = 'Polish',
  Portugalski = 'Portuguese',
  Keczua = 'Quechua',
  'Reto-Roman' = 'Romansh',
  Rundi = 'Rundi',
  Rumuński = 'Romanian',
  Rosyjski = 'Russian',
  Kinyarwanda = 'Kinyarwanda',
  Sanskryt = 'Sanskrit',
  Sardyński = 'Sardinian',
  Sindhi = 'Sindhi',
  'Północny sami' = 'Northern Sami',
  Sango = 'Sango',
  Syngaleski = 'Sinhala',
  Słowacki = 'Slovak',
  Słoweński = 'Slovenian',
  Samoński = 'Samoan',
  Shona = 'Shona',
  Somalijski = 'Somali',
  Albański = 'Albanian',
  Serbski = 'Serbian',
  Swati = 'Swati',
  'Sotho, Południowy' = 'Sotho, Southern',
  Sundajski = 'Sundanese',
  Szwedzki = 'Swedish',
  Suahili = 'Swahili',
  Tamilski = 'Tamil',
  Telugu = 'Telugu',
  Tadżycki = 'Tajik',
  Tajski = 'Thai',
  Tigrinia = 'Tigrinya',
  Turkmeński = 'Turkmen',
  Tagalski = 'Tagalog',
  Tswana = 'Tswana',
  Turecki = 'Turkish',
  Tsonga = 'Tsonga',
  Tatarski = 'Tatar',
  Twi = 'Twi',
  Tahitański = 'Tahitian',
  Ujgurski = 'Uyghur',
  Ukraiński = 'Ukrainian',
  Urdu = 'Urdu',
  Uzbecki = 'Uzbek',
  Venda = 'Venda',
  Wietnamski = 'Vietnamese',
  Volapük = 'Volapük',
  Waloński = 'Walloon',
  Wolof = 'Wolof',
  Xhosa = 'Xhosa',
  Jidysz = 'Yiddish',
  Joruba = 'Yoruba',
  Zhuang = 'Zhuang',
  Chiński = 'Chinese',
  Zuluski = 'Zulu',
}

export const ReversedLanguages = {
  aa: 'Afar',
  ab: 'Abchaski',
  ae: 'Awecki',
  af: 'Afrikaans',
  ak: 'Akan',
  am: 'Amharski',
  an: 'Aragoński',
  ar: 'Arabski',
  as: 'Asamski',
  av: 'Awaricki',
  ay: 'Ajmarski',
  az: 'Azerbejdżański',
  ba: 'Baszkirski',
  be: 'Białoruski',
  bg: 'Bułgarski',
  bh: 'Języki biharijskie',
  bi: 'Bislama',
  bm: 'Bambarski',
  bn: 'Bengalski',
  bo: 'Tybetański',
  br: 'Bretoński',
  bs: 'Bośniacki',
  ca: 'Kataloński; Walencki',
  ce: 'Czeczeński',
  ch: 'Chamorro',
  co: 'Korsykański',
  cr: 'Cree',
  cs: 'Czeski',
  cv: 'Czuwaszski',
  cy: 'Walon',
  da: 'Duński',
  de: 'Niemiecki',
  dz: 'Dzongkha',
  ee: 'Ewe',
  el: 'Grecki',
  en: 'Angielski',
  eo: 'Esperanto',
  es: 'Hiszpański',
  et: 'Estoński',
  eu: 'Baskijski',
  fa: 'Perski',
  ff: 'Fulah',
  fi: 'Fiński',
  fj: 'Fidżijski',
  fo: 'Wysp Owczych',
  fr: 'Francuski',
  fy: 'Fryzyjski zachodni',
  ga: 'Irlandzki',
  gl: 'Galicyjski',
  gn: 'Guarani',
  gu: 'Gujarati',
  gv: 'Manx',
  ha: 'Hausa',
  he: 'Hebrajski',
  hi: 'Hindi',
  ho: 'Hiri Motu',
  hr: 'Chorwacki',
  ht: 'Haiti Creole',
  hu: 'Węgierski',
  hy: 'Ormiański',
  hz: 'Herero',
  id: 'Indonezyjski',
  ig: 'Igbo',
  ii: 'Syczuanski Yi',
  ik: 'Inupiaq',
  io: 'Ido',
  is: 'Islandzki',
  it: 'Włoski',
  iu: 'Inuktitut',
  ja: 'Japoński',
  jv: 'Jawajski',
  ka: 'Gruziński',
  kg: 'Kongijski',
  kk: 'Kazachski',
  km: 'Język khmerski centralny',
  kn: 'Kannada',
  ko: 'Koreański',
  kr: 'Kanuri',
  ks: 'Kaszmirski',
  ku: 'Kurdski',
  kv: 'Komii',
  kw: 'Kornijski',
  ky: 'Kirgiski; Kyrgyz',
  la: 'Łaciński',
  lb: 'Luksemburski',
  lg: 'Gandijski',
  li: 'Limburski',
  ln: 'Lingala',
  lo: 'Laotański',
  lt: 'Litewski',
  lu: 'Luba-Katanga',
  lv: 'Łotewski',
  mg: 'Malgaski',
  mh: 'Marszalski',
  mi: 'Maoryski',
  mk: 'Macedoński',
  ml: 'Malayalam',
  mn: 'Mongolski',
  mr: 'Marathi',
  ms: 'Malajski',
  mt: 'Maltański',
  my: 'Birmański',
  na: 'Nauruański',
  ne: 'Nepalski',
  ng: 'Ndonga',
  nl: 'Holenderski',
  no: 'Norweski',
  oj: 'Ojibwa',
  om: 'Oromo',
  or: 'Orija',
  pa: 'Pendżabski',
  pi: 'Pali',
  pl: 'Polski',
  pt: 'Portugalski',
  qu: 'Keczua',
  rm: 'Reto-Roman',
  rn: 'Rundi',
  ro: 'Rumuński',
  ru: 'Rosyjski',
  rw: 'Kinyarwanda',
  sa: 'Sanskryt',
  sc: 'Sardyński',
  sd: 'Sindhi',
  se: 'Północny sami',
  sg: 'Sango',
  si: 'Syngaleski',
  sk: 'Słowacki',
  sl: 'Słoweński',
  sm: 'Samoński',
  sn: 'Shona',
  so: 'Somalijski',
  sq: 'Albański',
  sr: 'Serbski',
  ss: 'Swati',
  st: 'Sotho, Południowy',
  su: 'Sundajski',
  sv: 'Szwedzki',
  sw: 'Suahili',
  ta: 'Tamilski',
  te: 'Telugu',
  tg: 'Tadżycki',
  th: 'Tajski',
  ti: 'Tigrinia',
  tk: 'Turkmeński',
  tl: 'Tagalski',
  tn: 'Tswana',
  tr: 'Turecki',
  ts: 'Tsonga',
  tt: 'Tatarski',
  tw: 'Twi',
  ty: 'Tahitański',
  ug: 'Ujgurski',
  uk: 'Ukraiński',
  ur: 'Urdu',
  uz: 'Uzbecki',
  ve: 'Venda',
  vi: 'Wietnamski',
  vo: 'Volapük',
  wa: 'Waloński',
  wo: 'Wolof',
  xh: 'Xhosa',
  yi: 'Jidysz',
  yo: 'Joruba',
  za: 'Zhuang',
  zh: 'Chiński',
  zu: 'Zuluski',
} as const;
