export const symbols = {
  bookMapper: Symbol('bookMapper'),
  bookRepository: Symbol('bookRepository'),
  createBookCommandHandler: Symbol('createBookCommandHandler'),
  updateBookCommandHandler: Symbol('updateBookCommandHandler'),
  deleteBookCommandHandler: Symbol('deleteBookCommandHandler'),
  findBookQueryHandler: Symbol('findBookQueryHandler'),
  findBooksQueryHandler: Symbol('findBooksQueryHandler'),
  bookHttpController: Symbol('bookHttpController'),
  bookAdminHttpController: Symbol('bookAdminHttpController'),

  genreMapper: Symbol('genreMapper'),
  genreRepository: Symbol('genreRepository'),
  createGenreCommandHandler: Symbol('createGenreCommandHandler'),
  updateGenreCommandHandler: Symbol('updateGenreCommandHandler'),
  deleteGenreCommandHandler: Symbol('deleteGenreCommandHandler'),
  findGenresQueryHandler: Symbol('findGenresQueryHandler'),
  genreHttpController: Symbol('genreHttpController'),
  genreAdminHttpController: Symbol('genreAdminHttpController'),

  userBookMapper: Symbol('userBookMapper'),
  userBookRepository: Symbol('userBookRepository'),
  createUserBookCommandHandler: Symbol('createUserBookCommandHandler'),
  updateUserBookCommandHandler: Symbol('updateUserBookCommandHandler'),
  uploadUserBookImageCommandHandler: Symbol('uploadUserBookImageCommandHandler'),
  deleteUserBooksCommandHandler: Symbol('deleteUserBooksCommandHandler'),
  findUserBookQueryHandler: Symbol('findUserBookQueryHandler'),
  findUserBooksQueryHandler: Symbol('findUserBooksQueryHandler'),
  userBookHttpController: Symbol('userBookHttpController'),

  authorMapper: Symbol('authorMapper'),
  authorRepository: Symbol('authorRepository'),
  createAuthorCommandHandler: Symbol('createAuthorCommandHandler'),
  updateAuthorCommandHandler: Symbol('updateAuthorCommandHandler'),
  deleteAuthorCommandHandler: Symbol('deleteAuthorCommandHandler'),
  findAuthorsQueryHandler: Symbol('findAuthorsQueryHandler'),
  authorHttpController: Symbol('authorHttpController'),
  authorAdminHttpController: Symbol('authorAdminHttpController'),

  bookReadingMapper: Symbol('bookReadingMapper'),
  bookReadingRepository: Symbol('bookReadingRepository'),
  createBookReadingCommandHandler: Symbol('createBookReadingCommandHandler'),
  updateBookReadingCommandHandler: Symbol('updateBookReadingCommandHandler'),
  deleteBookReadingCommandHandler: Symbol('deleteBookReadingCommandHandler'),
  findBookReadingsQueryHandler: Symbol('findBookReadingsQueryHandler'),
  bookReadingHttpController: Symbol('bookReadingHttpController'),

  quoteMapper: Symbol('quoteMapper'),
  quoteRepository: Symbol('quoteRepository'),
  createQuoteCommandHandler: Symbol('createQuoteCommandHandler'),
  updateQuoteCommandHandler: Symbol('updateQuoteCommandHandler'),
  deleteQuoteCommandHandler: Symbol('deleteQuoteCommandHandler'),
  findQuotesQueryHandler: Symbol('findQuotesQueryHandler'),
  quoteHttpController: Symbol('quoteHttpController'),

  borrowingMapper: Symbol('borrowingMapper'),
  borrowingRepository: Symbol('borrowingRepository'),
  createBorrowingCommandHandler: Symbol('createBorrowingCommandHandler'),
  updateBorrowingCommandHandler: Symbol('updateBorrowingCommandHandler'),
  deleteBorrowingCommandHandler: Symbol('deleteBorrowingCommandHandler'),
  findBorrowingsQueryHandler: Symbol('findBorrowingsQueryHandler'),
  borrowingHttpController: Symbol('borrowingHttpController'),

  collectionMapper: Symbol('collectionMapper'),
  collectionRepository: Symbol('collectionRepository'),
  createCollectionCommandHandler: Symbol('createCollectionCommandHandler'),
  updateCollectionCommandHandler: Symbol('updateCollectionCommandHandler'),
  deleteCollectionCommandHandler: Symbol('deleteCollectionCommandHandler'),
  findCollectionsQueryHandler: Symbol('findCollectionsQueryHandler'),
  collectionHttpController: Symbol('collectionHttpController'),

  bookChangeRequestMapper: Symbol('bookChangeRequestMapper'),
  bookChangeRequestRepository: Symbol('bookChangeRequestRepository'),
  createBookChangeRequestCommandHandler: Symbol('createBookChangeRequestCommandHandler'),
  applyBookChangeRequestCommandHandler: Symbol('applyBookChangeRequestCommandHandler'),
  deleteBookChangeRequestCommandHandler: Symbol('deleteBookChangeRequestCommandHandler'),
  findBookChangeRequestsQueryHandler: Symbol('findBookChangeRequestsQueryHandler'),
  bookChangeRequestHttpController: Symbol('bookChangeRequestHttpController'),
  bookChangeRequestAdminHttpController: Symbol('bookChangeRequestAdminHttpController'),
};

export const bookSymbols = {
  bookHttpController: symbols.bookHttpController,
  bookAdminHttpController: symbols.bookAdminHttpController,
  userBookHttpController: symbols.userBookHttpController,
  bookRepository: symbols.bookRepository,
  userBookRepository: symbols.userBookRepository,
  genreHttpController: symbols.genreHttpController,
  genreAdminHttpController: symbols.genreAdminHttpController,
  authorHttpController: symbols.authorHttpController,
  authorAdminHttpController: symbols.authorAdminHttpController,
  bookReadingHttpController: symbols.bookReadingHttpController,
  borrowingHttpController: symbols.borrowingHttpController,
  quoteHttpController: symbols.quoteHttpController,
  collectionHttpController: symbols.collectionHttpController,
  bookChangeRequestHttpController: symbols.bookChangeRequestHttpController,
  bookChangeRequestAdminHttpController: symbols.bookChangeRequestAdminHttpController,
};
