export const languagesArray = [
  { code: 'aa', name: 'Afar' },
  { code: 'ab', name: 'Abkhazian' },
  { code: 'ae', name: 'Avestan' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'ak', name: 'Akan' },
  { code: 'am', name: 'Amharic' },
  { code: 'an', name: 'Aragonese' },
  { code: 'ar', name: 'Arabic' },
  { code: 'as', name: 'Assamese' },
  { code: 'av', name: 'Avaric' },
  { code: 'ay', name: 'Aymara' },
  { code: 'az', name: 'Azerbaijani' },
  { code: 'ba', name: 'Bashkir' },
  { code: 'be', name: 'Belarusian' },
  { code: 'bg', name: 'Bulgarian' },
  { code: 'bh', name: 'Bihari languages' },
  { code: 'bi', name: 'Bislama' },
  { code: 'bm', name: 'Bambara' },
  { code: 'bn', name: 'Bengali' },
  { code: 'bo', name: 'Tibetan' },
  { code: 'br', name: 'Breton' },
  { code: 'bs', name: 'Bosnian' },
  { code: 'ca', name: 'Catalan; Valencian' },
  { code: 'ce', name: 'Chechen' },
  { code: 'ch', name: 'Chamorro' },
  { code: 'co', name: 'Corsican' },
  { code: 'cr', name: 'Cree' },
  { code: 'cs', name: 'Czech' },
  { code: 'cv', name: 'Chuvash' },
  { code: 'cy', name: 'Welsh' },
  { code: 'da', name: 'Danish' },
  { code: 'de', name: 'German' },
  { code: 'dz', name: 'Dzongkha' },
  { code: 'ee', name: 'Ewe' },
  { code: 'el', name: 'Greek' },
  { code: 'en', name: 'English' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'es', name: 'Spanish' },
  { code: 'et', name: 'Estonian' },
  { code: 'eu', name: 'Basque' },
  { code: 'fa', name: 'Persian' },
  { code: 'ff', name: 'Fulah' },
  { code: 'fi', name: 'Finnish' },
  { code: 'fj', name: 'Fijian' },
  { code: 'fo', name: 'Faroese' },
  { code: 'fr', name: 'French' },
  { code: 'fy', name: 'Western Frisian' },
  { code: 'ga', name: 'Irish' },
  { code: 'gl', name: 'Galician' },
  { code: 'gn', name: 'Guarani' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'gv', name: 'Manx' },
  { code: 'ha', name: 'Hausa' },
  { code: 'he', name: 'Hebrew' },
  { code: 'hi', name: 'Hindi' },
  { code: 'ho', name: 'Hiri Motu' },
  { code: 'hr', name: 'Croatian' },
  { code: 'ht', name: 'Haitian' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'hy', name: 'Armenian' },
  { code: 'hz', name: 'Herero' },
  { code: 'id', name: 'Indonesian' },
  { code: 'ig', name: 'Igbo' },
  { code: 'ii', name: 'Sichuan Yi' },
  { code: 'ik', name: 'Inupiaq' },
  { code: 'io', name: 'Ido' },
  { code: 'is', name: 'Icelandic' },
  { code: 'it', name: 'Italian' },
  { code: 'iu', name: 'Inuktitut' },
  { code: 'ja', name: 'Japanese' },
  { code: 'jv', name: 'Javanese' },
  { code: 'ka', name: 'Georgian' },
  { code: 'kg', name: 'Kongo' },
  { code: 'kk', name: 'Kazakh' },
  { code: 'km', name: 'Central Khmer' },
  { code: 'kn', name: 'Kannada' },
  { code: 'ko', name: 'Korean' },
  { code: 'kr', name: 'Kanuri' },
  { code: 'ks', name: 'Kashmiri' },
  { code: 'ku', name: 'Kurdish' },
  { code: 'kv', name: 'Komi' },
  { code: 'kw', name: 'Cornish' },
  { code: 'ky', name: 'Kirghiz; Kyrgyz' },
  { code: 'la', name: 'Latin' },
  { code: 'lb', name: 'Luxembourgish' },
  { code: 'lg', name: 'Ganda' },
  { code: 'li', name: 'Limburgan' },
  { code: 'ln', name: 'Lingala' },
  { code: 'lo', name: 'Lao' },
  { code: 'lt', name: 'Lithuanian' },
  { code: 'lu', name: 'Luba-Katanga' },
  { code: 'lv', name: 'Latvian' },
  { code: 'mg', name: 'Malagasy' },
  { code: 'mh', name: 'Marshallese' },
  { code: 'mi', name: 'Maori' },
  { code: 'mk', name: 'Macedonian' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'mn', name: 'Mongolian' },
  { code: 'mr', name: 'Marathi' },
  { code: 'ms', name: 'Malay' },
  { code: 'mt', name: 'Maltese' },
  { code: 'my', name: 'Burmese' },
  { code: 'na', name: 'Nauru' },
  { code: 'ne', name: 'Nepali' },
  { code: 'ng', name: 'Ndonga' },
  { code: 'nl', name: 'Dutch' },
  { code: 'no', name: 'Norwegian' },
  { code: 'oj', name: 'Ojibwa' },
  { code: 'om', name: 'Oromo' },
  { code: 'or', name: 'Oriya' },
  { code: 'pa', name: 'Punjabi' },
  { code: 'pi', name: 'Pali' },
  { code: 'pl', name: 'Polish' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'qu', name: 'Quechua' },
  { code: 'rm', name: 'Romansh' },
  { code: 'rn', name: 'Rundi' },
  { code: 'ro', name: 'Romanian' },
  { code: 'ru', name: 'Russian' },
  { code: 'rw', name: 'Kinyarwanda' },
  { code: 'sa', name: 'Sanskrit' },
  { code: 'sc', name: 'Sardinian' },
  { code: 'sd', name: 'Sindhi' },
  { code: 'se', name: 'Northern Sami' },
  { code: 'sg', name: 'Sango' },
  { code: 'si', name: 'Sinhala' },
  { code: 'sk', name: 'Slovak' },
  { code: 'sl', name: 'Slovenian' },
  { code: 'sm', name: 'Samoan' },
  { code: 'sn', name: 'Shona' },
  { code: 'so', name: 'Somali' },
  { code: 'sq', name: 'Albanian' },
  { code: 'sr', name: 'Serbian' },
  { code: 'ss', name: 'Swati' },
  { code: 'st', name: 'Sotho, Southern' },
  { code: 'su', name: 'Sundanese' },
  { code: 'sv', name: 'Swedish' },
  { code: 'sw', name: 'Swahili' },
  { code: 'ta', name: 'Tamil' },
  { code: 'te', name: 'Telugu' },
  { code: 'tg', name: 'Tajik' },
  { code: 'th', name: 'Thai' },
  { code: 'ti', name: 'Tigrinya' },
  { code: 'tk', name: 'Turkmen' },
  { code: 'tl', name: 'Tagalog' },
  { code: 'tn', name: 'Tswana' },
  { code: 'tr', name: 'Turkish' },
  { code: 'ts', name: 'Tsonga' },
  { code: 'tt', name: 'Tatar' },
  { code: 'tw', name: 'Twi' },
  { code: 'ty', name: 'Tahitian' },
  { code: 'ug', name: 'Uyghur' },
  { code: 'uk', name: 'Ukrainian' },
  { code: 'ur', name: 'Urdu' },
  { code: 'uz', name: 'Uzbek' },
  { code: 've', name: 'Venda' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'vo', name: 'Volapük' },
  { code: 'wa', name: 'Walloon' },
  { code: 'wo', name: 'Wolof' },
  { code: 'xh', name: 'Xhosa' },
  { code: 'yi', name: 'Yiddish' },
  { code: 'yo', name: 'Yoruba' },
  { code: 'za', name: 'Zhuang' },
  { code: 'zh', name: 'Chinese' },
  { code: 'zu', name: 'Zulu' },
];

export enum Languages {
  Afar = 'Afar',
  Abkhazian = 'Abchaski',
  Avestan = 'Awecki',
  Afrikaans = 'Afrikaans',
  Akan = 'Akan',
  Amharic = 'Amharski',
  Aragonese = 'Aragoński',
  Arabic = 'Arabski',
  Assamese = 'Asamski',
  Avaric = 'Awaricki',
  Aymara = 'Ajmarski',
  Azerbaijani = 'Azerbejdżański',
  Bashkir = 'Baszkirski',
  Belarusian = 'Białoruski',
  Bulgarian = 'Bułgarski',
  'Bihari languages' = 'Języki biharijskie',
  Bislama = 'Bislama',
  Bambara = 'Bambarski',
  Bengali = 'Bengalski',
  Tibetan = 'Tybetański',
  Breton = 'Bretoński',
  Bosnian = 'Bośniacki',
  'Catalan; Valencian' = 'Kataloński; Walencki',
  Chechen = 'Czeczeński',
  Chamorro = 'Chamorro',
  Corsican = 'Korsykański',
  Cree = 'Cree',
  Czech = 'Czeski',
  Chuvash = 'Czuwaszski',
  Welsh = 'Walon',
  Danish = 'Duński',
  German = 'Niemiecki',
  Dzongkha = 'Dzongkha',
  Ewe = 'Ewe',
  Greek = 'Grecki',
  English = 'Angielski',
  Esperanto = 'Esperanto',
  Spanish = 'Hiszpański',
  Estonian = 'Estoński',
  Basque = 'Baskijski',
  Persian = 'Perski',
  Fulah = 'Fulah',
  Finnish = 'Fiński',
  Fijian = 'Fidżijski',
  Faroese = 'Wysp Owczych',
  French = 'Francuski',
  'Western Frisian' = 'Fryzyjski zachodni',
  Irish = 'Irlandzki',
  Galician = 'Galicyjski',
  Guarani = 'Guarani',
  Gujarati = 'Gujarati',
  Manx = 'Manx',
  Hausa = 'Hausa',
  Hebrew = 'Hebrajski',
  Hindi = 'Hindi',
  'Hiri Motu' = 'Hiri Motu',
  Croatian = 'Chorwacki',
  Haitian = 'Haiti Creole',
  Hungarian = 'Węgierski',
  Armenian = 'Ormiański',
  Herero = 'Herero',
  Indonesian = 'Indonezyjski',
  Igbo = 'Igbo',
  'Sichuan Yi' = 'Syczuanski Yi',
  Inupiaq = 'Inupiak',
  Ido = 'Ido',
  Icelandic = 'Islandzki',
  Italian = 'Włoski',
  Inuktitut = 'Inuktitut',
  Japanese = 'Japoński',
  Javanese = 'Jawajski',
  Georgian = 'Gruziński',
  Kongo = 'Kongijski',
  Kazakh = 'Kazachski',
  'Central Khmer' = 'Język khmerski centralny',
  Kannada = 'Kannada',
  Korean = 'Koreański',
  Kanuri = 'Kanuri',
  Kashmiri = 'Kaszmirski',
  Kurdish = 'Kurdski',
  Komi = 'Komii',
  Cornish = 'Kornijski',
  'Kirghiz; Kyrgyz' = 'Kirgiski; Kyrgyz',
  Latin = 'Łaciński',
  Luxembourgish = 'Luksemburski',
  Ganda = 'Gandijski',
  Limburgan = 'Limburski',
  Lingala = 'Lingala',
  Lao = 'Laotański',
  Lithuanian = 'Litewski',
  'Luba-Katanga' = 'Luba-Katanga',
  Latvian = 'Łotewski',
  Malagasy = 'Malgaski',
  Marshallese = 'Marszalski',
  Maori = 'Maoryski',
  Macedonian = 'Macedoński',
  Malayalam = 'Malayalam',
  Mongolian = 'Mongolski',
  Marathi = 'Marathi',
  Malay = 'Malajski',
  Maltese = 'Maltański',
  Burmese = 'Birmański',
  Nauru = 'Nauruański',
  Nepali = 'Nepalski',
  Ndonga = 'Ndonga',
  Dutch = 'Holenderski',
  Norwegian = 'Norweski',
  Ojibwa = 'Ojibwa',
  Oriya = 'Orija',
  Punjabi = 'Pendżabski',
  Pali = 'Pali',
  Polish = 'Polski',
  Portuguese = 'Portugalski',
  Quechua = 'Keczua',
  Romansh = 'Reto-Roman',
  Rundi = 'Rundi',
  Romanian = 'Rumuński',
  Russian = 'Rosyjski',
  Kinyarwanda = 'Kinyarwanda',
  Sanskrit = 'Sanskryt',
  Sardinian = 'Sardyński',
  Sindhi = 'Sindhi',
  'Northern Sami' = 'Północny sami',
  Sango = 'Sango',
  Sinhala = 'Syngaleski',
  Slovak = 'Słowacki',
  Slovenian = 'Słoweński',
  Samoan = 'Samoński',
  Shona = 'Shona',
  Somali = 'Somalijski',
  Albanian = 'Albański',
  Serbian = 'Serbski',
  Swati = 'Swati',
  'Sotho, Southern' = 'Sotho, Południowy',
  Sundanese = 'Sundajski',
  Swedish = 'Szwedzki',
  Swahili = 'Suahili',
  Tamil = 'Tamilski',
  Telugu = 'Telugu',
  Tajik = 'Tadżycki',
  Thai = 'Tajski',
  Tigrinya = 'Tigrinia',
  Turkmen = 'Turkmeński',
  Tagalog = 'Tagalski',
  Tswana = 'Tswana',
  Turkish = 'Turecki',
  Tsonga = 'Tsonga',
  Tatar = 'Tatarski',
  Twi = 'Twi',
  Tahitian = 'Tahitański',
  Uyghur = 'Ujgurski',
  Ukrainian = 'Ukraiński',
  Urdu = 'Urdu',
  Uzbek = 'Uzbecki',
  Venda = 'Venda',
  Vietnamese = 'Wietnamski',
  Volapük = 'Volapük',
  Walloon = 'Waloński',
  Wolof = 'Wolof',
  Xhosa = 'Xhosa',
  Yiddish = 'Jidysz',
  Yoruba = 'Joruba',
  Zhuang = 'Zhuang',
  Chinese = 'Chiński',
  Zulu = 'Zuluski',
}
