import { Language } from '@common/contracts';

export const languagesArray: { code: Language; name: string }[] = [
  { code: Language.aa, name: 'Afar' },
  { code: Language.ab, name: 'Abkhazian' },
  { code: Language.ae, name: 'Avestan' },
  { code: Language.af, name: 'Afrikaans' },
  { code: Language.ak, name: 'Akan' },
  { code: Language.am, name: 'Amharic' },
  { code: Language.an, name: 'Aragonese' },
  { code: Language.ar, name: 'Arabic' },
  { code: Language.as, name: 'Assamese' },
  { code: Language.av, name: 'Avaric' },
  { code: Language.ay, name: 'Aymara' },
  { code: Language.az, name: 'Azerbaijani' },
  { code: Language.ba, name: 'Bashkir' },
  { code: Language.be, name: 'Belarusian' },
  { code: Language.bg, name: 'Bulgarian' },
  { code: Language.bh, name: 'Bihari languages' },
  { code: Language.bi, name: 'Bislama' },
  { code: Language.bm, name: 'Bambara' },
  { code: Language.bn, name: 'Bengali' },
  { code: Language.bo, name: 'Tibetan' },
  { code: Language.br, name: 'Breton' },
  { code: Language.bs, name: 'Bosnian' },
  { code: Language.ca, name: 'Catalan; Valencian' },
  { code: Language.ce, name: 'Chechen' },
  { code: Language.ch, name: 'Chamorro' },
  { code: Language.co, name: 'Corsican' },
  { code: Language.cr, name: 'Cree' },
  { code: Language.cs, name: 'Czech' },
  { code: Language.cv, name: 'Chuvash' },
  { code: Language.cy, name: 'Welsh' },
  { code: Language.da, name: 'Danish' },
  { code: Language.de, name: 'German' },
  { code: Language.dz, name: 'Dzongkha' },
  { code: Language.ee, name: 'Ewe' },
  { code: Language.el, name: 'Greek' },
  { code: Language.en, name: 'English' },
  { code: Language.eo, name: 'Esperanto' },
  { code: Language.es, name: 'Spanish' },
  { code: Language.et, name: 'Estonian' },
  { code: Language.eu, name: 'Basque' },
  { code: Language.fa, name: 'Persian' },
  { code: Language.ff, name: 'Fulah' },
  { code: Language.fi, name: 'Finnish' },
  { code: Language.fj, name: 'Fijian' },
  { code: Language.fo, name: 'Faroese' },
  { code: Language.fr, name: 'French' },
  { code: Language.fy, name: 'Western Frisian' },
  { code: Language.ga, name: 'Irish' },
  { code: Language.gl, name: 'Galician' },
  { code: Language.gn, name: 'Guarani' },
  { code: Language.gu, name: 'Gujarati' },
  { code: Language.gv, name: 'Manx' },
  { code: Language.ha, name: 'Hausa' },
  { code: Language.he, name: 'Hebrew' },
  { code: Language.hi, name: 'Hindi' },
  { code: Language.ho, name: 'Hiri Motu' },
  { code: Language.hr, name: 'Croatian' },
  { code: Language.ht, name: 'Haitian' },
  { code: Language.hu, name: 'Hungarian' },
  { code: Language.hy, name: 'Armenian' },
  { code: Language.hz, name: 'Herero' },
  { code: Language.id, name: 'Indonesian' },
  { code: Language.ig, name: 'Igbo' },
  { code: Language.ii, name: 'Sichuan Yi' },
  { code: Language.ik, name: 'Inupiaq' },
  { code: Language.io, name: 'Ido' },
  { code: Language.is, name: 'Icelandic' },
  { code: Language.it, name: 'Italian' },
  { code: Language.iu, name: 'Inuktitut' },
  { code: Language.ja, name: 'Japanese' },
  { code: Language.jv, name: 'Javanese' },
  { code: Language.ka, name: 'Georgian' },
  { code: Language.kg, name: 'Kongo' },
  { code: Language.kk, name: 'Kazakh' },
  { code: Language.km, name: 'Central Khmer' },
  { code: Language.kn, name: 'Kannada' },
  { code: Language.ko, name: 'Korean' },
  { code: Language.kr, name: 'Kanuri' },
  { code: Language.ks, name: 'Kashmiri' },
  { code: Language.ku, name: 'Kurdish' },
  { code: Language.kv, name: 'Komi' },
  { code: Language.kw, name: 'Cornish' },
  { code: Language.ky, name: 'Kirghiz; Kyrgyz' },
  { code: Language.la, name: 'Latin' },
  { code: Language.lb, name: 'Luxembourgish' },
  { code: Language.lg, name: 'Ganda' },
  { code: Language.li, name: 'Limburgan' },
  { code: Language.ln, name: 'Lingala' },
  { code: Language.lo, name: 'Lao' },
  { code: Language.lt, name: 'Lithuanian' },
  { code: Language.lu, name: 'Luba-Katanga' },
  { code: Language.lv, name: 'Latvian' },
  { code: Language.mg, name: 'Malagasy' },
  { code: Language.mh, name: 'Marshallese' },
  { code: Language.mi, name: 'Maori' },
  { code: Language.mk, name: 'Macedonian' },
  { code: Language.ml, name: 'Malayalam' },
  { code: Language.mn, name: 'Mongolian' },
  { code: Language.mr, name: 'Marathi' },
  { code: Language.ms, name: 'Malay' },
  { code: Language.mt, name: 'Maltese' },
  { code: Language.my, name: 'Burmese' },
  { code: Language.na, name: 'Nauru' },
  { code: Language.ne, name: 'Nepali' },
  { code: Language.ng, name: 'Ndonga' },
  { code: Language.nl, name: 'Dutch' },
  { code: Language.no, name: 'Norwegian' },
  { code: Language.oj, name: 'Ojibwa' },
  { code: Language.om, name: 'Oromo' },
  { code: Language.or, name: 'Oriya' },
  { code: Language.pa, name: 'Punjabi' },
  { code: Language.pi, name: 'Pali' },
  { code: Language.pl, name: 'Polish' },
  { code: Language.pt, name: 'Portuguese' },
  { code: Language.qu, name: 'Quechua' },
  { code: Language.rm, name: 'Romansh' },
  { code: Language.rn, name: 'Rundi' },
  { code: Language.ro, name: 'Romanian' },
  { code: Language.ru, name: 'Russian' },
  { code: Language.rw, name: 'Kinyarwanda' },
  { code: Language.sa, name: 'Sanskrit' },
  { code: Language.sc, name: 'Sardinian' },
  { code: Language.sd, name: 'Sindhi' },
  { code: Language.se, name: 'Northern Sami' },
  { code: Language.sg, name: 'Sango' },
  { code: Language.si, name: 'Sinhala' },
  { code: Language.sk, name: 'Slovak' },
  { code: Language.sl, name: 'Slovenian' },
  { code: Language.sm, name: 'Samoan' },
  { code: Language.sn, name: 'Shona' },
  { code: Language.so, name: 'Somali' },
  { code: Language.sq, name: 'Albanian' },
  { code: Language.sr, name: 'Serbian' },
  { code: Language.ss, name: 'Swati' },
  { code: Language.st, name: 'Sotho, Southern' },
  { code: Language.su, name: 'Sundanese' },
  { code: Language.sv, name: 'Swedish' },
  { code: Language.sw, name: 'Swahili' },
  { code: Language.ta, name: 'Tamil' },
  { code: Language.te, name: 'Telugu' },
  { code: Language.tg, name: 'Tajik' },
  { code: Language.th, name: 'Thai' },
  { code: Language.ti, name: 'Tigrinya' },
  { code: Language.tk, name: 'Turkmen' },
  { code: Language.tl, name: 'Tagalog' },
  { code: Language.tn, name: 'Tswana' },
  { code: Language.tr, name: 'Turkish' },
  { code: Language.ts, name: 'Tsonga' },
  { code: Language.tt, name: 'Tatar' },
  { code: Language.tw, name: 'Twi' },
  { code: Language.ty, name: 'Tahitian' },
  { code: Language.ug, name: 'Uyghur' },
  { code: Language.uk, name: 'Ukrainian' },
  { code: Language.ur, name: 'Urdu' },
  { code: Language.uz, name: 'Uzbek' },
  { code: Language.ve, name: 'Venda' },
  { code: Language.vi, name: 'Vietnamese' },
  { code: Language.vo, name: 'Volapük' },
  { code: Language.wa, name: 'Walloon' },
  { code: Language.wo, name: 'Wolof' },
  { code: Language.xh, name: 'Xhosa' },
  { code: Language.yi, name: 'Yiddish' },
  { code: Language.yo, name: 'Yoruba' },
  { code: Language.za, name: 'Zhuang' },
  { code: Language.zh, name: 'Chinese' },
  { code: Language.zu, name: 'Zulu' },
];

export enum Languages {
  Afar = 'Afar',
  Abkhazian = 'Abchaski',
  Avestan = 'Awecki',
  Afrikaans = 'Afrikaans',
  Akan = 'Akan',
  Amharic = 'Amharski',
  Aragonese = 'Aragoński',
  Arabic = 'Arabski',
  Assamese = 'Asamski',
  Avaric = 'Awaricki',
  Aymara = 'Ajmarski',
  Azerbaijani = 'Azerbejdżański',
  Bashkir = 'Baszkirski',
  Belarusian = 'Białoruski',
  Bulgarian = 'Bułgarski',
  'Bihari languages' = 'Języki biharijskie',
  Bislama = 'Bislama',
  Bambara = 'Bambarski',
  Bengali = 'Bengalski',
  Tibetan = 'Tybetański',
  Breton = 'Bretoński',
  Bosnian = 'Bośniacki',
  'Catalan; Valencian' = 'Kataloński; Walencki',
  Chechen = 'Czeczeński',
  Chamorro = 'Chamorro',
  Corsican = 'Korsykański',
  Cree = 'Cree',
  Czech = 'Czeski',
  Chuvash = 'Czuwaszski',
  Welsh = 'Walon',
  Danish = 'Duński',
  German = 'Niemiecki',
  Dzongkha = 'Dzongkha',
  Ewe = 'Ewe',
  Greek = 'Grecki',
  English = 'Angielski',
  Esperanto = 'Esperanto',
  Spanish = 'Hiszpański',
  Estonian = 'Estoński',
  Basque = 'Baskijski',
  Persian = 'Perski',
  Fulah = 'Fulah',
  Finnish = 'Fiński',
  Fijian = 'Fidżijski',
  Faroese = 'Wysp Owczych',
  French = 'Francuski',
  'Western Frisian' = 'Fryzyjski zachodni',
  Irish = 'Irlandzki',
  Galician = 'Galicyjski',
  Guarani = 'Guarani',
  Gujarati = 'Gujarati',
  Manx = 'Manx',
  Hausa = 'Hausa',
  Hebrew = 'Hebrajski',
  Hindi = 'Hindi',
  'Hiri Motu' = 'Hiri Motu',
  Croatian = 'Chorwacki',
  Haitian = 'Haiti Creole',
  Hungarian = 'Węgierski',
  Armenian = 'Ormiański',
  Herero = 'Herero',
  Indonesian = 'Indonezyjski',
  Igbo = 'Igbo',
  'Sichuan Yi' = 'Syczuanski Yi',
  Inupiaq = 'Inupiak',
  Ido = 'Ido',
  Icelandic = 'Islandzki',
  Italian = 'Włoski',
  Inuktitut = 'Inuktitut',
  Japanese = 'Japoński',
  Javanese = 'Jawajski',
  Georgian = 'Gruziński',
  Kongo = 'Kongijski',
  Kazakh = 'Kazachski',
  'Central Khmer' = 'Język khmerski centralny',
  Kannada = 'Kannada',
  Korean = 'Koreański',
  Kanuri = 'Kanuri',
  Kashmiri = 'Kaszmirski',
  Kurdish = 'Kurdski',
  Komi = 'Komii',
  Cornish = 'Kornijski',
  'Kirghiz; Kyrgyz' = 'Kirgiski; Kyrgyz',
  Latin = 'Łaciński',
  Luxembourgish = 'Luksemburski',
  Ganda = 'Gandijski',
  Limburgan = 'Limburski',
  Lingala = 'Lingala',
  Lao = 'Laotański',
  Lithuanian = 'Litewski',
  'Luba-Katanga' = 'Luba-Katanga',
  Latvian = 'Łotewski',
  Malagasy = 'Malgaski',
  Marshallese = 'Marszalski',
  Maori = 'Maoryski',
  Macedonian = 'Macedoński',
  Malayalam = 'Malayalam',
  Mongolian = 'Mongolski',
  Marathi = 'Marathi',
  Malay = 'Malajski',
  Maltese = 'Maltański',
  Burmese = 'Birmański',
  Nauru = 'Nauruański',
  Nepali = 'Nepalski',
  Ndonga = 'Ndonga',
  Dutch = 'Holenderski',
  Norwegian = 'Norweski',
  Ojibwa = 'Ojibwa',
  Oriya = 'Orija',
  Punjabi = 'Pendżabski',
  Pali = 'Pali',
  Polish = 'Polski',
  Portuguese = 'Portugalski',
  Quechua = 'Keczua',
  Romansh = 'Reto-Roman',
  Rundi = 'Rundi',
  Romanian = 'Rumuński',
  Russian = 'Rosyjski',
  Kinyarwanda = 'Kinyarwanda',
  Sanskrit = 'Sanskryt',
  Sardinian = 'Sardyński',
  Sindhi = 'Sindhi',
  'Northern Sami' = 'Północny sami',
  Sango = 'Sango',
  Sinhala = 'Syngaleski',
  Slovak = 'Słowacki',
  Slovenian = 'Słoweński',
  Samoan = 'Samoński',
  Shona = 'Shona',
  Somali = 'Somalijski',
  Albanian = 'Albański',
  Serbian = 'Serbski',
  Swati = 'Swati',
  'Sotho, Southern' = 'Sotho, Południowy',
  Sundanese = 'Sundajski',
  Swedish = 'Szwedzki',
  Swahili = 'Suahili',
  Tamil = 'Tamilski',
  Telugu = 'Telugu',
  Tajik = 'Tadżycki',
  Thai = 'Tajski',
  Tigrinya = 'Tigrinia',
  Turkmen = 'Turkmeński',
  Tagalog = 'Tagalski',
  Tswana = 'Tswana',
  Turkish = 'Turecki',
  Tsonga = 'Tsonga',
  Tatar = 'Tatarski',
  Twi = 'Twi',
  Tahitian = 'Tahitański',
  Uyghur = 'Ujgurski',
  Ukrainian = 'Ukraiński',
  Urdu = 'Urdu',
  Uzbek = 'Uzbecki',
  Venda = 'Venda',
  Vietnamese = 'Wietnamski',
  Volapük = 'Volapük',
  Walloon = 'Waloński',
  Wolof = 'Wolof',
  Xhosa = 'Xhosa',
  Yiddish = 'Jidysz',
  Yoruba = 'Joruba',
  Zhuang = 'Zhuang',
  Chinese = 'Chiński',
  Zulu = 'Zuluski',
}
