export enum BookDomainActionType {
  deleteAuthor = 'deleteAuthor',
  addAuthor = 'addAuthor',
  updateTitle = 'updateTitle',
  updateIsbn = 'updateIsbn',
  updatePublisher = 'updatePublisher',
  updateReleaseYear = 'updateReleaseYear',
  updateLanguage = 'updateLanguage',
  updateTranslator = 'updateTranslator',
  updateFormat = 'updateFormat',
  updatePages = 'updatePages',
  updateFrontCoverImageUrl = 'updateFrontCoverImageUrl',
  updateBackCoverImageUrl = 'updateBackCoverImageUrl',
  updateStatus = 'updateStatus',
  updateBookshelf = 'updateBookshelf',
}
