/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as VerifyEmailIndexImport } from './routes/verifyEmail/index'
import { Route as ShelvesIndexImport } from './routes/shelves/index'
import { Route as ResetPasswordIndexImport } from './routes/resetPassword/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as NewPasswordIndexImport } from './routes/newPassword/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as BookshelfBookshelfIdImport } from './routes/bookshelf/$bookshelfId'
import { Route as BookshelfSearchIndexImport } from './routes/bookshelf/search/index'
import { Route as BookshelfCreateBookIdImport } from './routes/bookshelf/createBook/$id'
import { Route as BookshelfSearchResultIndexImport } from './routes/bookshelf/search/result/index'
import { Route as AdminTabsChangeRequestsIndexImport } from './routes/admin/tabs/changeRequests/index'
import { Route as AdminTabsBooksIndexImport } from './routes/admin/tabs/books/index'
import { Route as AdminTabsAuthorsIndexImport } from './routes/admin/tabs/authors/index'
import { Route as BookshelfSearchCreateBookshelfIdImport } from './routes/bookshelf/search/create/$bookshelfId'
import { Route as BookTabsQuotationsTabBookIdImport } from './routes/book/tabs/quotationsTab/$bookId'
import { Route as BookTabsGradesTabBookIdImport } from './routes/book/tabs/gradesTab/$bookId'
import { Route as BookTabsBasicDataTabBookIdImport } from './routes/book/tabs/basicDataTab/$bookId'
import { Route as AdminTabsChangeRequestsIdImport } from './routes/admin/tabs/changeRequests/$id'
import { Route as AdminTabsBooksEditIdImport } from './routes/admin/tabs/books/edit/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VerifyEmailIndexRoute = VerifyEmailIndexImport.update({
  path: '/verifyEmail/',
  getParentRoute: () => rootRoute,
} as any)

const ShelvesIndexRoute = ShelvesIndexImport.update({
  path: '/shelves/',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordIndexRoute = ResetPasswordIndexImport.update({
  path: '/resetPassword/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const NewPasswordIndexRoute = NewPasswordIndexImport.update({
  path: '/newPassword/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const BookshelfBookshelfIdRoute = BookshelfBookshelfIdImport.update({
  path: '/bookshelf/$bookshelfId',
  getParentRoute: () => rootRoute,
} as any)

const BookshelfSearchIndexRoute = BookshelfSearchIndexImport.update({
  path: '/bookshelf/search/',
  getParentRoute: () => rootRoute,
} as any)

const BookshelfCreateBookIdRoute = BookshelfCreateBookIdImport.update({
  path: '/bookshelf/createBook/$id',
  getParentRoute: () => rootRoute,
} as any)

const BookshelfSearchResultIndexRoute = BookshelfSearchResultIndexImport.update(
  {
    path: '/bookshelf/search/result/',
    getParentRoute: () => rootRoute,
  } as any,
)

const AdminTabsChangeRequestsIndexRoute =
  AdminTabsChangeRequestsIndexImport.update({
    path: '/admin/tabs/changeRequests/',
    getParentRoute: () => rootRoute,
  } as any)

const AdminTabsBooksIndexRoute = AdminTabsBooksIndexImport.update({
  path: '/admin/tabs/books/',
  getParentRoute: () => rootRoute,
} as any)

const AdminTabsAuthorsIndexRoute = AdminTabsAuthorsIndexImport.update({
  path: '/admin/tabs/authors/',
  getParentRoute: () => rootRoute,
} as any)

const BookshelfSearchCreateBookshelfIdRoute =
  BookshelfSearchCreateBookshelfIdImport.update({
    path: '/bookshelf/search/create/$bookshelfId',
    getParentRoute: () => rootRoute,
  } as any)

const BookTabsQuotationsTabBookIdRoute =
  BookTabsQuotationsTabBookIdImport.update({
    path: '/book/tabs/quotationsTab/$bookId',
    getParentRoute: () => rootRoute,
  } as any)

const BookTabsGradesTabBookIdRoute = BookTabsGradesTabBookIdImport.update({
  path: '/book/tabs/gradesTab/$bookId',
  getParentRoute: () => rootRoute,
} as any)

const BookTabsBasicDataTabBookIdRoute = BookTabsBasicDataTabBookIdImport.update(
  {
    path: '/book/tabs/basicDataTab/$bookId',
    getParentRoute: () => rootRoute,
  } as any,
)

const AdminTabsChangeRequestsIdRoute = AdminTabsChangeRequestsIdImport.update({
  path: '/admin/tabs/changeRequests/$id',
  getParentRoute: () => rootRoute,
} as any)

const AdminTabsBooksEditIdRoute = AdminTabsBooksEditIdImport.update({
  path: '/admin/tabs/books/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bookshelf/$bookshelfId': {
      preLoaderRoute: typeof BookshelfBookshelfIdImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/newPassword/': {
      preLoaderRoute: typeof NewPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/resetPassword/': {
      preLoaderRoute: typeof ResetPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/shelves/': {
      preLoaderRoute: typeof ShelvesIndexImport
      parentRoute: typeof rootRoute
    }
    '/verifyEmail/': {
      preLoaderRoute: typeof VerifyEmailIndexImport
      parentRoute: typeof rootRoute
    }
    '/bookshelf/createBook/$id': {
      preLoaderRoute: typeof BookshelfCreateBookIdImport
      parentRoute: typeof rootRoute
    }
    '/bookshelf/search/': {
      preLoaderRoute: typeof BookshelfSearchIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/tabs/changeRequests/$id': {
      preLoaderRoute: typeof AdminTabsChangeRequestsIdImport
      parentRoute: typeof rootRoute
    }
    '/book/tabs/basicDataTab/$bookId': {
      preLoaderRoute: typeof BookTabsBasicDataTabBookIdImport
      parentRoute: typeof rootRoute
    }
    '/book/tabs/gradesTab/$bookId': {
      preLoaderRoute: typeof BookTabsGradesTabBookIdImport
      parentRoute: typeof rootRoute
    }
    '/book/tabs/quotationsTab/$bookId': {
      preLoaderRoute: typeof BookTabsQuotationsTabBookIdImport
      parentRoute: typeof rootRoute
    }
    '/bookshelf/search/create/$bookshelfId': {
      preLoaderRoute: typeof BookshelfSearchCreateBookshelfIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/tabs/authors/': {
      preLoaderRoute: typeof AdminTabsAuthorsIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/tabs/books/': {
      preLoaderRoute: typeof AdminTabsBooksIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/tabs/changeRequests/': {
      preLoaderRoute: typeof AdminTabsChangeRequestsIndexImport
      parentRoute: typeof rootRoute
    }
    '/bookshelf/search/result/': {
      preLoaderRoute: typeof BookshelfSearchResultIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/tabs/books/edit/$id': {
      preLoaderRoute: typeof AdminTabsBooksEditIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BookshelfBookshelfIdRoute,
  LoginIndexRoute,
  NewPasswordIndexRoute,
  ProfileIndexRoute,
  RegisterIndexRoute,
  ResetPasswordIndexRoute,
  ShelvesIndexRoute,
  VerifyEmailIndexRoute,
  BookshelfCreateBookIdRoute,
  BookshelfSearchIndexRoute,
  AdminTabsChangeRequestsIdRoute,
  BookTabsBasicDataTabBookIdRoute,
  BookTabsGradesTabBookIdRoute,
  BookTabsQuotationsTabBookIdRoute,
  BookshelfSearchCreateBookshelfIdRoute,
  AdminTabsAuthorsIndexRoute,
  AdminTabsBooksIndexRoute,
  AdminTabsChangeRequestsIndexRoute,
  BookshelfSearchResultIndexRoute,
  AdminTabsBooksEditIdRoute,
])

/* prettier-ignore-end */
