name: Deployment (BE)

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c apps/backend/fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_BACKEND_TOKEN }}
