name: Test

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  test:
    env:
      NODE_ENV: development

    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20.10.0
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    # - run: npx playwright install --with-deps # To be determined if needed
      # Stop sending SIGTTOU for background output, run in the background, kill after tests
    - run: |
        stty -tostop npm run dev --workspace=@apps/frontend > /dev/null &
        FRONTENT_DEV_SERVER_PID=$!
        NODE_ENV=ci npm run test:e2e:run
        kill $FRONTENT_DEV_SERVER_PID
